version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: leaduj-postgres
    environment:
      POSTGRES_USER: leaduj
      POSTGRES_PASSWORD: leaduj
      POSTGRES_DB: leaduj
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leaduj"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db_data:


